services:
  - type: cron
    name: my-crawler
    env: python
    plan: free
    schedule: "*/20 * * * *"   # 每 20 分钟运行一次
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
